
[build]
  publish = "public/"
  functions = "api/"
  ignore = "git diff --quiet HEAD^ HEAD ../../"

[[redirects]]
  SPA only
  from = "/*"
  to = "/__app.html"
  status = 200

  # SSR and SPA
  # from = "/*"
  # to = "/.netlify/functions/ssr"
  # status = 200
